### PR TITLE
Show keyboard icon in advertisement & fix for #199

### PR DESCRIPTION
**Pull request by Webunity**
Added the possibility to set the appearance of the keyboard demo.

### CODE REVIEW

**Comment by Webunity** [comment]
When exposing 2 times '0x03' in the `adv_data` i couldn't pair anymore; so i replaced:
```
// 16-bit Service UUIDs
0x03, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE & 0xff, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE >> 8,
```
with
```
// Set keyboard icon
0x03, 0x19, 0xC1, 0x03,
```

And it started working again, showing a keyboard icon.

**Comment by mringwal** [comment]
Thanks for the suggestion. What device did you use for testing? iOS devices, e.g. an iPhone, don't show icons in the Bluetooth settings (at least I didn't see one yet).

As far as I know, it's necessary (by the spec) to list the ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE in the advertisement. 

The 0x03 is only the length of the following item, in this case 0x19 = BLUETOOTH_DATA_TYPE_APPEARANCE, and it should not be important if there was another AD element that has len 3 (1 byte for type, 2 bytes for data)

**Comment by Webunity** [comment]
I tested on an Android phone, so we might need both.

**Comment by Webunity** [comment]
also fixes #199

**Comment by mringwal** [comment]
Thanks. I've added the appearance values to both HOG demos in ae856536.

**Pull request closed without merging**
