### PR TITLE
Some spelling fixes, mostly in docs

### PR DESCRIPTION
**Pull request by mattkelly**
Just some minor spelling fixes I collected while perusing. Pretty awesome documentation, by the way!

### CODE REVIEW

**Comment by mringwal** [comment]
Thanks a lot! For the congrats as well as the spelling fixed. I've applied your patch on the develop tree instead of accepting the pull request (since we merge from develop to master).

I've seen your toy-ble-stack project. Do you want to use the ESP32 for that? I'd like to run BTstack on that one as well. If you try porting it or get started with your stack, please let me know. I'm going to order an ESP32 breakout board, too.

**Comment by mattkelly** [comment]
Will do! The ESP32 SDK doesn't provide as much access to internal transport layers as I'd like, so I have an issue raised to see what's possible: https://github.com/espressif/esp-idf/issues/357. Of course you can still hook up to the VHCI layer instead.

**Comment by mringwal** [comment]
I see. Interesting. The VHCI seems to allow abstraction of the underlying RTOS.

Does libbtdm_app.a.implement API_vhci_host_send_packet etc? Do I need to follow the getting started to get libbtdm_app.a?

**Comment by mattkelly** [comment]
Yup, libbtdm_app.a implements the VHCI API. It's a submodule of esp-idf, directly available here https://github.com/espressif/esp32-bt-lib. Following getting started works.

I just picked up an ESP32 myself so I'm still figuring things out, but it seems like they have bluedroid half-ported with a lot of missing functionality so far, though basic GATT server/client looks to be there. It'll probably require some slight tweaking of the build system to rip out bluedroid while saving VHCI; will probably investigate that soon.

**Comment by mringwal** [comment]
I'm not used to submodules yet.. 

Ok. component/bt/bt.c inits bluedroid - so not doing that might already be enough to use VHCI directly. Feel free to mail me directly matthias at bluekitchen-gmbh dot com.

**Pull request closed without merging**
