### PR TITLE
Fixup of the ESP32 port 

### PR DESCRIPTION
**Pull request by timkoers**
This pull request includes:

- Using the correct bluetooth mode (taken from sdkconfig)
- Fixed lwip paths in the CMakeLists.txt file
- ESP32 source audio instance

### CODE REVIEW

**Comment by timkoers** [comment]
I'm used the Gerrit workflow of patchsets and rebases, so sorry for the commit spam

**Comment by mringwal** [comment]
Thanks, I've picked the "Enable BTDM and BLE only mode to work" on develop.
The audio input, I'd like to actually try out before merging.

What's the issue with the IDF_PATH? I see a \\ -> / replacement. I guess mixing path separators doesn't work well in mingw?

**Comment by timkoers** [comment]
> Thanks, I've picked the "Enable BTDM and BLE only mode to work" on develop. The audio input, I'd like to actually try out before merging.
No worries!

> What's the issue with the IDF_PATH? I see a \ -> / replacement. I guess mixing path separators doesn't work well in mingw?

I'm not using mingw, I'm using PlatformIO which also uses CMake and fails to understand the path seperators

**Comment by mringwal** [comment]
ok.. so lets replace mingw with 'that operating system that uses backslashes" to properly name the root cause :).

**Comment by mringwal** [comment]
I've merged Ricardo's patch for the CMakeFile that uses idf_component_register, and I'm closing this one.

**Pull request closed without merging**
