### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hyprhare**
Refine grammar and phrasing.
Re-order for logical flow of information.
#Housekeeping

### CODE REVIEW

**Comment by mringwal** [comment]
Hi bennj. Thanks for your suggestions. I'll go over them in detail.

We moved the links to the documentation & mailing list up before so that people would see it better / not miss it.

The bullet lists for the HCI Transports use up some additional space, for the coming next, it wouldn't hurt if it's at the end or so.

**Comment by hyprhare** [comment]
I've re-ordered the sections per my understanding of your request. Please let me know of any additional adjustments you would seek to have made.

**Comment by mringwal** [comment]
Thanks for updating the request. We don't like the look of the `something` emphasis. We have adapted some of your textual suggestion on the develop branch. Currently, all changes are first applied to the 'develop' branch and which is then merged into the 'master' branch. Merging from master onto develop, breaks the links to the build server.  

Thanks again. What brings you to BTstack?

**Comment by hyprhare** [comment]
Wurd, not a problem!

I'm looking for a base-level bluetooth library I can utilize in order to expand the capabilities of my smartphone beyond just the default file-share and audio-stream features.

**Pull request closed without merging**
